# .streamlit/secrets.toml
# please change with your own credential if you want to run it locally

[google]
gemini_api_key = "---------------"

[reddit]
client_id = "---------------"
client_secret = "---------------"
user_agent="script:mental-health-bot:v1.0 (by /u/"---------------")"
