[google]
gemini_api_key = "YOUR_GEMINI_KEY"

[reddit]
client_id = "YOUR_REDDIT_CLIENT_ID"
client_secret = "YOUR_REDDIT_CLIENT_SECRET"
user_agent = "script:mental-health-bot:v1.0 (by /u/YOUR_REDDIT_USERNAME)"
